### ISSUE TITLE
LSMtool depends on wscaccess, not available in KERN-dev 

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#102]
https://github.com/darafferty/LSMTool/issues/13

LSMtool should be updated to use astropy. backporting wcsaccess to KERN-dev gives problems:

```
running install_scripts
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "wcsaxes/__init__.py", line 18, in <module>
    from .patches import *
  File "wcsaxes/patches.py", line 10, in <module>
    from astropy.coordinates.angles import rotation_matrix
ImportError: cannot import name rotation_matrix
```

**Comment by gijzelaerr** [comment]
prefactor is also affected as a dependency on lsmtool

**Comment by gijzelaerr** [comment]
and factor

**Comment by gijzelaerr** [comment]
this issue has been resolved.
