### ISSUE TITLE
ddfacet is missing python-ephem dependency

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#120]
```
λ  /usr/bin/DDF.py
 - 18:07:55 - AsyncProcessPool          | Fixing parent process to vthread 0
 - 18:07:55 - AsyncProcessPool          | Worker affinities not specified, leaving unset
Traceback (most recent call last):
  File "/usr/bin/DDF.py", line 42, in <module>
    from DDFacet.Imager import ClassDeconvMachine
  File "/usr/lib/python2.7/dist-packages/DDFacet/Imager/ClassDeconvMachine.py", line 21, in <module>
    from ClassFacetMachineTessel import ClassFacetMachineTessel as ClassFacetMachine
  File "/usr/lib/python2.7/dist-packages/DDFacet/Imager/ClassFacetMachineTessel.py", line 21, in <module>
    from DDFacet.Imager import ClassFacetMachine
  File "/usr/lib/python2.7/dist-packages/DDFacet/Imager/ClassFacetMachine.py", line 21, in <module>
    import ClassDDEGridMachine
  File "/usr/lib/python2.7/dist-packages/DDFacet/Imager/ClassDDEGridMachine.py", line 35, in <module>
    from DDFacet.Data import ClassVisServer
  File "/usr/lib/python2.7/dist-packages/DDFacet/Data/ClassVisServer.py", line 25, in <module>
    import ClassMS
  File "/usr/lib/python2.7/dist-packages/DDFacet/Data/ClassMS.py", line 26, in <module>
    import ephem
ImportError: No module named ephem
❗ 
```

**Comment by gijzelaerr** [comment]
added and uploaded to kern-dev.
