### ISSUE TITLE
DPPP dysco error using Kern lofar package

### ISSUE THREAD

**Issue by mknapp55** [kernsuite/packaging#202]
Similar problem to #196 :

```
mknapp@GALATEA:/mnt/d/lofar/V830Tau/workdir_L693114$ DPPP /home/mknapp/LiLF/parsets/LOFAR_cal/DPPP-flag.parset msin="/mnt/d/lofar/V830Tau/workdir_L693114/L693114_SB001_uv.MS" ant.baseline="DE*;FR*;SE*;UK*;IR*;PL*"
log4cplus:ERROR No appenders could be found for logger (LCS.Common).
log4cplus:ERROR Please initialize the log4cplus system properly.

**** uncaught exception ****

Backtrace follows:
#0  0x7f6c599de76b in LOFAR::Exception::terminate() at ??:0
#1  0x7f6c596c2ab6 in std::rethrow_exception(std::__exception_ptr::exception_ptr) at ??:0
#2  0x7f6c596c2af1 in std::terminate() at ??:0
#3  0x7f6c596c2d24 in __cxa_throw at ??:0
#4  0x7f6c56cfe264 in casa::DataManager::unknownDataManager(casa::String const&, casa::Record const&) at ??:0
#5  0x7f6c56c33e14 in casa::ColumnSet::getFile(casa::AipsIO&, casa::Table&, unsigned int, bool, casa::TSMOption const&) at ??:0
#6  0x7f6c56c53587 in casa::PlainTable::PlainTable(casa::AipsIO&, unsigned int, casa::String const&, casa::String const&, unsigned int, int, casa::TableLock const&, casa::TSMOption const&, bool, unsigned int) at ??:0
#7  0x7f6c56c9de9b in casa::Table::makeBaseTable(casa::String const&, casa::String const&, int, casa::TableLock const&, casa::TSMOption const&, bool, unsigned int) at ??:0
#8  0x7f6c56c9fd3c in casa::Table::open(casa::String const&, casa::String const&, int, casa::TableLock const&, casa::TSMOption const&) at ??:0
#9  0x7f6c56ca01a2 in casa::Table::Table(casa::String const&, casa::TableLock const&, casa::Table::TableOption, casa::TSMOption const&) at ??:0
#10 0x7f6c57cc2235 in casa::MSTable<casa::MSMainEnums::PredefinedColumns, casa::MSMainEnums::PredefinedKeywords>::MSTable(casa::String const&, casa::TableLock const&, casa::Table::TableOption) at ??:0
#11 0x7f6c57c5ba69 in casa::MeasurementSet::MeasurementSet(casa::String const&, casa::TableLock const&, casa::Table::TableOption) at ??:0
#12 0x7f6c5a29c2c4 in LOFAR::DPPP::MSReader::MSReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LOFAR::ParameterSet const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) at ??:0
#13 0x7f6c5a26224f in LOFAR::DPPP::DPRun::makeSteps(LOFAR::ParameterSet const&) at ??:0
#14 0x7f6c5a264092 in LOFAR::DPPP::DPRun::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**) at ??:0#15 0x7f6c5ac050b7 in main at ??:0
terminate called after throwing an instance of 'casa::DataManUnknownCtor'
  what():  Table DataManager error: Data Manager class DyscoStMan is not registered
  Check (DY)LD_LIBRARY_PATH matches the libraries used during the build of DyscoStMan
Aborted (core dumped)
```
lofar package version should be latest:

```
mknapp@GALATEA:/mnt/d/lofar/V830Tau/workdir_L693114$ sudo apt-get install lofar
Reading package lists... Done
Building dependency tree
Reading state information... Done
lofar is already the newest version (3.1.7-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

The issue in #196 is resolved (the script works now) so this seems to be a new but related problem.

**Comment by gijzelaerr** [comment]
What KERN are you using? The lofar package is not available in KERN-5 and KERN-dev yet.

**Comment by mknapp55** [comment]
I don't know exactly - must be KERN-4?  In any case, lofar versions 3.1+ should be dysco compatible according to ASTRON (see [here](http://old.astron.nl/radio-observatory/lofar-data-processing/dysco-compression/compressing-lofar-measurement-sets-using-d)).

**Comment by gijzelaerr** [comment]
this issue is quite outdated by now and we are working on KERN-6. dp3 is in there and the lofar packages also. Please let us know if this issue persists in the latest KERN-6
