### ISSUE TITLE
can't pip install bdsf

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#210]
Trying to pip install it into a virgin virtualenv, it falls over. This smells like a packaging/dependency issue, rather than a problem with BDS* itself, so I'm reporting it here. @gijzelaerr, @Athanaseus, any ideas?

```
$ virtualenv ~/.venv/test
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/oms/.venv/test/bin/python2
Also creating executable in /home/oms/.venv/test/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
oms@miles:~/projects$ source ~/.venv/test/bin/activate
(test) oms@miles:~/projects$ pip install bdsf
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting bdsf
  Using cached https://files.pythonhosted.org/packages/c5/f6/073bb849e61c61e88e93accab3766afb0fc35d0981224584d31829a4bc38/bdsf-1.8.15.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/oms/.venv/test/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cYNRsH/bdsf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cYNRsH/bdsf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-cYNRsH/bdsf/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cYNRsH/bdsf/setup.py", line 7, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                                                                                                   
(test) oms@miles:~/projects$ 
 ```

**Comment by o-smirnov** [comment]
If I manually ``pip install numpy``, then ``pip install bdsf`` gets a little further, up to:
```    
    Building libminpack
    error: [Errno 2] No such file or directory
```

**Comment by gijzelaerr** [comment]
kern has little to do with the pip packaging of bdsf, please report the issue here https://github.com/lofar-astron/PyBDSF
