### ISSUE TITLE
Tables used by the python-casacore measures seem to be missing from pip install

### ISSUE THREAD

**Issue by sjperkins** [kernsuite/packaging#3]
- Xenial 16.04 install
- Installed kern casacore-dev with `apt install`
- Installed python-casacore in a virtualenv using `pip install`
- Ran montblanc test case which makes use of pyrap.measures
- Complaints about missing tables crop up, one producing a SEVERE log message.

``` bash
(mb) sperkins@simon-Y700:~/work/ska/code/montblanc/montblanc/tests$ python test_cmp_vis.py
test_cmp_visibilities (__main__.TestCmpVis)
Test visibilities produced by montblanc and meqtrees ... 2016-07-18 16:16:05    WARN    MeasIERS::findTab (file /build/casacore-QQbZwk/casacore-2.1.0/measures/Measures/MeasIERS.cc, line 381)  Requested data table IERSeop97 cannot be found in the searched directories:
2016-07-18 16:16:05 WARN    MeasIERS::findTab (file /build/casacore-QQbZwk/casacore-2.1.0/measures/Measures/MeasIERS.cc, line 381)+ /usr/share/casacore/data/ephemerides/
2016-07-18 16:16:05 WARN    MeasIERS::findTab (file /build/casacore-QQbZwk/casacore-2.1.0/measures/Measures/MeasIERS.cc, line 381)+ /usr/share/casacore/data/geodetic/
2016-07-18 16:16:05 WARN    MeasIERS::findTab (file /build/casacore-QQbZwk/casacore-2.1.0/measures/Measures/MeasIERS.cc, line 381)  Requested data table IERSpredict cannot be found in the searched directories:
2016-07-18 16:16:05 WARN    MeasIERS::findTab (file /build/casacore-QQbZwk/casacore-2.1.0/measures/Measures/MeasIERS.cc, line 381)+ /usr/share/casacore/data/ephemerides/
2016-07-18 16:16:05 WARN    MeasIERS::findTab (file /build/casacore-QQbZwk/casacore-2.1.0/measures/Measures/MeasIERS.cc, line 381)+ /usr/share/casacore/data/geodetic/
2016-07-18 16:16:05 INFO    MeasIERS::fillMeas(MeasIERS::Files, Double)     Requested JD 51583 is outside the range of the IERS (Earth axis data) table.
2016-07-18 16:16:05 INFO    MeasIERS::fillMeas(MeasIERS::Files, Double) +   Calculations will proceed with less precision
2016-07-18 16:16:05 WARN    MeasIERS::findTab (file /build/casacore-QQbZwk/casacore-2.1.0/measures/Measures/MeasIERS.cc, line 381)  Requested data table TAI_UTC cannot be found in the searched directories:
2016-07-18 16:16:05 WARN    MeasIERS::findTab (file /build/casacore-QQbZwk/casacore-2.1.0/measures/Measures/MeasIERS.cc, line 381)+ /usr/share/casacore/data/ephemerides/
2016-07-18 16:16:05 WARN    MeasIERS::findTab (file /build/casacore-QQbZwk/casacore-2.1.0/measures/Measures/MeasIERS.cc, line 381)+ /usr/share/casacore/data/geodetic/
2016-07-18 16:16:05 SEVERE  MeasTable::dUTC(Double) (file /build/casacore-QQbZwk/casacore-2.1.0/measures/Measures/MeasTable.cc, line 4383)  Cannot read leap second table TAI_UTC
ERROR

======================================================================
ERROR: test_cmp_visibilities (__main__.TestCmpVis)
Test visibilities produced by montblanc and meqtrees
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cmp_vis.py", line 365, in test_cmp_visibilities
    vis_output=Options.VISIBILITY_OUTPUT_RESIDUALS)
  File "test_cmp_vis.py", line 282, in get_v4_output
    with montblanc.rime_solver(slvr_cfg) as slvr:
  File "/home/sperkins/work/ska/code/montblanc/montblanc/__init__.py", line 148, in rime_solver
    return montblanc.factory.rime_solver(slvr_cfg)
  File "/home/sperkins/work/ska/code/montblanc/montblanc/factory.py", line 175, in rime_solver
    return create_rime_solver_from_ms(RimeSolver, slvr_cfg)
  File "/home/sperkins/work/ska/code/montblanc/montblanc/factory.py", line 147, in create_rime_solver_from_ms
    loader.load(slvr, slvr_cfg)
  File "/home/sperkins/work/ska/code/montblanc/montblanc/impl/rime/v4/loaders/loaders.py", line 126, in load
    parallactic_angles = mbu.parallactic_angles(phase_dir, ref_ant_position, times)
  File "/home/sperkins/work/ska/code/montblanc/montblanc/util/__init__.py", line 459, in parallactic_angles
    pm.posangle(field_centre, zenith).get_value("deg") for t in times])
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/casacore/measures/__init__.py", line 933, in posangle
    return _measures.posangle(self, m0, m1)
RuntimeError: 2016-07-18 16:16:05   SEVERE  MeasTable::dUTC(Double) (file /build/casacore-QQbZwk/casacore-2.1.0/measures/Measures/MeasTable.cc, line 4383)  Cannot read leap second table TAI_UTC

----------------------------------------------------------------------
Ran 1 test in 0.136s

FAILED (errors=1)
(mb) sperkins@simon-Y700:~/work/ska/code/montblanc/montblanc/tests$ 

```

**Comment by sjperkins** [comment]
I guess this should probably be logged against python-casacore?

**Comment by gijzelaerr** [comment]
did you install `casacore-data` ? This is not a forced dependency.

**Comment by sjperkins** [comment]
Ah, no I didn't have casacore-data installed. After installation this works correctly.

Thanks, closing
